#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Auto-generated by goshbuild — DO NOT EDIT
# Self-contained Go module runner — works on Linux (GH Actions) and macOS
# ----------------------------------------------------------------------------
set -euo pipefail

# ── Portability helpers ───────────────────────────────────────────────────

# sha256 of a file — supports GNU (sha256sum) and BSD/macOS (shasum)
_sha256_file() {
    if command -v sha256sum &>/dev/null; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        echo "🔴 [goshbuild] ERROR: no sha256 tool found (sha256sum or shasum required)" >&2; exit 1
    fi
}

# sha256 of a string
_sha256_str() {
    if command -v sha256sum &>/dev/null; then
        printf '%s' "$1" | sha256sum | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        printf '%s' "$1" | shasum -a 256 | awk '{print $1}'
    else
        echo "🔴 [goshbuild] ERROR: no sha256 tool found" >&2; exit 1
    fi
}

# base64 decode from stdin — GNU uses --decode, BSD/macOS uses -D
_b64_decode() {
    if base64 --decode /dev/null &>/dev/null 2>&1; then
        base64 --decode
    else
        base64 -D
    fi
}

_is_truthy() {
    case "${1:-}" in
        1|true|TRUE|yes|YES|on|ON)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

_enable_verbose_logging() {
    local log_file="$1"

    mkdir -p "$(dirname "${log_file}")"
    : > "${log_file}"

    if command -v tee >/dev/null 2>&1; then
        exec > >(tee -a "${log_file}") 2>&1
    else
        exec >> "${log_file}" 2>&1
    fi

    echo "📜 [goshbuild] Transcript → ${log_file}"

    if _is_truthy "${GOSHBUILD_TRACE:-0}"; then
        set -x
    fi
}

# Map uname -m kernel names to Go arch names.
# Without this, x86_64 in the cache key would never match go env GOARCH=amd64.
_resolve_goarch() {
    case "${1:-}" in
        x86_64)        echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        i386|i686)     echo "386"   ;;
        armv7l|armv6l) echo "arm"   ;;
        *)             echo "${1}"  ;;
    esac
}

# Clear a directory's contents before re-extracting sources.
# This avoids stale files surviving across payload changes.
_clear_dir_contents() {
    local dir="$1"
    local entries=()

    mkdir -p "${dir}"
    shopt -s dotglob nullglob
    entries=( "${dir}"/* )
    shopt -u dotglob nullglob

    if (( ${#entries[@]} > 0 )); then
        rm -rf "${entries[@]}"
    fi
}

# ── 1. Identity & home ────────────────────────────────────────────────────
MODULE_SAFE="github_com_example_demo-app"
PAYLOAD_SHA256="c69ec29a28b95a077752a721565bd14b59353dc98eb10e8d22af1db24950c497"   # sha256 of the embedded tar.gz;
                                       # any source change → new hash → rebuild

# MMM_HOME lets CI pin the cache to a persistent volume between runs.
BASE_HOME="${MMM_HOME:-${TMPDIR:-/tmp}}"
APP_HOME="${BASE_HOME}/goshbuild/${MODULE_SAFE}"
GOCACHE="${APP_HOME}/gocache"

SRC_DIR="${APP_HOME}/src"
BIN_DIR="${APP_HOME}/bin"
OUT_DIR="${APP_HOME}/out"
DECODE_TMP="${APP_HOME}/payload_verify.tar.gz"  # temp file used for checksum check

mkdir -p "${SRC_DIR}" "${BIN_DIR}" "${OUT_DIR}" "${GOCACHE}"
export GOCACHE

# ── 2. Cache key ──────────────────────────────────────────────────────────
# Four-part key — all must match or binary is rebuilt:
#   module_safe → isolates projects sharing the same MMM_HOME
#   GOOS/GOARCH → arch/OS mismatch → rebuild
#   go version  → toolchain upgrade → rebuild
#   payload sha → source change → rebuild
GOOS="${GOOS:-$(go env GOOS 2>/dev/null || uname -s | tr '[:upper:]' '[:lower:]')}"

if _raw_arch="$(go env GOARCH 2>/dev/null)"; then
    GOARCH="${GOARCH:-${_raw_arch}}"
else
    # Fall back to uname -m and map to Go arch names
    GOARCH="${GOARCH:-$(_resolve_goarch "$(uname -m)")}"
fi

GO_VERSION="$(go version 2>/dev/null | awk '{print $3}' || echo 'unknown')"

CACHE_KEY="${MODULE_SAFE}__${GOOS}_${GOARCH}__${GO_VERSION}__${PAYLOAD_SHA256}"
CACHE_KEY_HASH="$(_sha256_str "${CACHE_KEY}")"

BINARY="${BIN_DIR}/${CACHE_KEY_HASH}/app"

if _is_truthy "${GOSHBUILD_VERBOSE:-0}"; then
    RUNNER_LOG_DIR="${GOSHBUILD_LOG_DIR:-${APP_HOME}/logs}"
    _enable_verbose_logging "${RUNNER_LOG_DIR}/runner-${CACHE_KEY_HASH}-$$.log"
fi

# ── 3. Build (cache miss path) ────────────────────────────────────────────
if [[ ! -x "${BINARY}" ]]; then
    echo "🔨 [goshbuild] Cache miss — building ${MODULE_SAFE} (${GOOS}/${GOARCH}, ${GO_VERSION})" >&2

    # 3a. Find the payload marker line
    PAYLOAD_LINE="$(grep -n '^__PAYLOAD_B64__$' "$0" | cut -d: -f1)"
    if [[ -z "${PAYLOAD_LINE}" ]]; then
        echo "🔴 [goshbuild] ERROR: payload marker not found in runner script" >&2
        exit 1
    fi
    PAYLOAD_START=$(( PAYLOAD_LINE + 1 ))

    # 3b. Decode into a temp file, then verify sha256 BEFORE extracting.
    #     If the runner was truncated or corrupted, we fail fast with a clear message
    #     rather than letting tar produce a confusing partial extraction.
    tail -n "+${PAYLOAD_START}" "$0" | _b64_decode > "${DECODE_TMP}"

    ACTUAL_SHA="$(_sha256_file "${DECODE_TMP}")"
    if [[ "${ACTUAL_SHA}" != "${PAYLOAD_SHA256}" ]]; then
        echo "🔴 [goshbuild] ERROR: payload checksum mismatch — runner may be corrupted!" >&2
        echo "   expected : ${PAYLOAD_SHA256}" >&2
        echo "   actual   : ${ACTUAL_SHA}" >&2
        rm -f "${DECODE_TMP}"
        exit 1
    fi
    echo "✅ [goshbuild] Payload checksum verified (${ACTUAL_SHA:0:12}…)" >&2

    # 3c. Clear any previously extracted tree so deleted files do not linger.
    _clear_dir_contents "${SRC_DIR}"

    # 3d. Unpack verified tarball
    tar -xz -C "${SRC_DIR}" --strip-components=1 < "${DECODE_TMP}"
    rm -f "${DECODE_TMP}"

    # 3e. Compile
    mkdir -p "$(dirname "${BINARY}")"
    echo "⚙️  [goshbuild] go build → ${BINARY}" >&2
    (cd "${SRC_DIR}" && go build -o "${BINARY}" .) \
        || { echo "🔴 [goshbuild] ERROR: go build failed" >&2; exit 1; }

    echo "✅ [goshbuild] Build complete → ${BINARY}" >&2
else
    echo "⚡ [goshbuild] Cache hit → ${BINARY}" >&2
fi

# ── 4. Exec — forward ALL CLI args seamlessly ─────────────────────────────
# exec replaces this shell process with the Go binary — no PID wrapper,
# signals propagate directly, exit codes are exact.
# "$@" preserves every argument exactly as the caller passed them.
exec "${BINARY}" "$@"

# (Never reached — exec replaced this process)
__PAYLOAD_B64__
H4sIAAAAAAAAA+296Y7jSLYmWH+LT8HyyqmIKKUHxV2KvJHdlChR1EZSpNbsaAd3UeImrqIyY3Dn
x8zfBrov0OjGBRrzZzAPMD/6eeoFeh5hjNTi8iUis25XVhXmyhBwl0hbzjl2zrFzzO2zMEwvuFfD
EPnNr1fqoNAk+Zs6VUdp6vi7Xker56fyG5REaZpAcRKnf1NHcRxHfwOTvyJNl5LGiRrB8G/agWHu
ZdU3tGAvWJbr+OZfY/i/dTHO8287yTrVHvTAezD3qhe65sP53fso9d/rQRSlYfI+Xv/ZY3x9/nGS
Ioin84/hFAbmv/4r8Pui/Cuf/9//DknjCNEcHzH9DNbUeA39Hr7/CxbQHZMmwb1t+makJqYBawVs
B/FaSx3XgP/0j/8EswI8FhS4w/IKqC2brnWvB36igjkwYC6AvcBIXRMGagi6qFrkQbSN4cCHh46f
7uG3XA9m9MQJ/PgdDOYQ9lRdkP/SjMRmAt+baQCHTmhaquNCYIQ//dM/gn+wGESJqjmukxTw2nRD
M4pPr/4O/5V0x2sVIyk4sGAVthwg3VKscRqGgJEY5sZT+O2xSpx6R5m2ZBap5Fq9KR9DD8cqD2UH
b9/BP0IwKI4FAy/ilU3uM/jSCfyH7xHDzBA/dd3v4GRt+lXtsjzWufsGvYN/gtV8C7/5MYwcP4G/
QT+/qWqa7ouef7bbssK9Cpecfr3r2Lw0M/V1AN/9v//tn/4f+IeLnn6CO5OJMPkA+8FZdEkQuLAV
pICaR1HBQXQeNzJ3qROZxrs7+Ps/YN/B5t5JYLQaxnKgz88nIU4ATfZFpODr/4REK/4s+M3/Er85
M/7Y7C8l39cHuRL5ryPtL4sTeC+TImDD1IEzh60o8IBUDcevdLtU6TQ2Y+ATjhW+vdLo4wsWetAo
4uH4+lr6p47PLeGLRK6lA2Pf/wF9JqJnDV+yf67AXjHy4MQPSZQm6+JCgw6qARn/iH64/3wHO48D
oD+BmuZPymTa+akw45+WHfmnwP9JGL+7VClLZCZp5MP1Jw+/++7y9Y+vVkdfq27Gql5RafqqBqKE
zIy0IDYf3MC2gQJfSHYDXXXBT7vyDh9LBYGqF97WcCL4PgT8vAWffNWrWDvX/Hz37q6q9wH+/ulz
6BVjSEwT/voUmHtTBz19/7asChTz6VBVi1e0smr0bPzHumCeoGvl/U///ER5lUj1Yz1ywgT+0//x
H+FXeXic5HIQTpB7rSk/ZB+UCdPufLivf7577s3K1Wf/RN9HaginlfzuPXhrRr7pwuXXGFhLuW6q
kb4+PngPas9BhBekCejVib+F9w3qASgeMA4wCtAvHfzcmgVYWVOwKvsmmFawiiagAzuAy9CAE5hJ
u/dR9QyKeA89RGYcuJn5YAflKD+vqMfx3j01+6qzu2tFVMveKOInNfLK2qdq5Zcn1Ry8Qf3kUA3q
3VVv4NndU7UGDTPaLTvLKPeqt2fV/ngh66o3wAPg4LnW/x5uuyYIGFUYqK6pJ0FUvInhMloxfbBu
aqYVRCBSMe/NfRKpICTxbTgO0kg/zoECZA+rWeAYMXBNKlh2S7UAn9Moc7KysqpHQRzDoVq4gWrA
+lr17bLtg16O+wBGfTiP9szUwKujlT0+ArUix4w/vn33wvR+BJ8+H+vG6wBo6n0MG0Fiu4EGl6ZU
fjhyfu7j0gj5I/zuumH6suFZy9++Bdr/+1MXP/zbT5+BJdbhd++e6XYElozIKge4qnr3RNdPcRb6
HuYNUKmMs/4ArwOg+3/zcOprkdZIYKfDzoPMdDsf776SY91BIrMcCgz7IPcYsN59vDPxRl1tgsUB
Q1XVIDHd0hsa1qhbNNXU0Cahkyqh1VGqoaF6HSWbOKnXjbpOo2bTxHWiWer4dYRRmrnpaaZhgKAa
5Dzv7cN3T/z7V8rvQQBYnPT4pJKVZ/PNHAYr/rr6EpmV+6sc02j00BNGHdg1gVG0eRAxX/sZ4J1U
uAyRnbhUZDgL3BRMpGYmuWn6ZZwPFL7FyJ2qE6DUP547/HD/zY/KSGT5yYd7JPHCz0BLGFG81Ls0
+oxc/DECmj/OAmjACW2m3avqn9uW1SvagIOWJ+0HMMDT13Gk30EtfvzyDUid7iBhqrx8A5ztHcR2
2gLbeQBEP315MvBy+XSs4v1xQu5KUSemFx5DchCVGCDmiYDITX1bBlbVBwi6tuMTucBXlfwfKTx+
ORF1/HJiGrBv7ssYHz49uLIt7D3cvqwDf3PT+fPs7PdwF2jnfagCziryQcSngoDAA/n9aR0DcgRz
pUYFDHzwUVmTD6AhfMovH2LVOqq1A5Y2kKkCLxwFG+Dk49KMyui80uG4XHDPClm15wRBRo7rY9W+
XMMQEFV6Tnwc+to8ygZgSc1K9QcJbPWuDG6BWQEjSUM7Ug3zRYvzegAIqd69tMVz7ZKYj9WECzIw
l7eX5RsQhF2FSj/9dI4dYhCoJxH85ocPIP0zow+f3pSf3SCvPr8rg5YyYInU/KHkDHT+9klMcN3t
u+uw5RQyVMSUn0rrvXRTmu4l5gLTV86Wpurb0jtcgppjLh++iGe+1P3bZ3FJGWOeO3t3V7JShm6c
8DDrTGReGJ94OU/GE/k8TV7wz29KkVWxwZvU3/pB7r8BkSpUWdHDoLOs/NSVo3l4OE7C54czgadH
58Grr0/dPiDw0t9Dj5FL7t5epYSlJV8qVJFy6ZSYSTX42fiRqzpVJ5+RaoWBvhJ2ApJagvwi8JxM
x+PO5GEocGf39tjk9LCc1Ee3BiLd+LRyfyFBKMd92u1n5Lizc/+C7vtvvnkPmh1n7eKn8Pdwq9o7
entcToCZlQFTsn73d+G1SjH/8AP8OxCtn1wymB/ghD99uhLsJe39v59kDu1HhkoPVj0tZfZUs+C3
J81CLpr1LfxEs457DtDJtnD1Pdx1gCmV7uvsSTw1AikDXG50VtXOijjkx53KLCIzhO99+M2/f3g4
v2uB7PjhmzLbr5fZvg6yiXvjA3xvoaec7cj6/aFk/LrD5+w/EcGrmf8zMv0gOe21OP55I/CYYh05
vXT6ZFfgmi9ZYSbKx29ARHpNGFyDURCPXiSlvYfZY44PrL4MUy6r8bcV9fBxvT7HVa1OV5h04Mdg
//2po7Lwx6DrRG2ugrQMfNarPdByUT/uqJvGt3AO8gDVccEPsFrlIEoEA1fxPgx8Xaza5lWvEVB0
0F0CPH8ZXlUZRrmFDdYqIwVLglpmI1Yal8/L5dAp84ATfYF/pC8pBwNze1e7ckClfKpYoZrbq52Q
Yx7+GMics1imrUyZYem5rr1UFbk8q/9EO8ow6NISDPi7j9facvaD/1J9uYRKj4svMKTTHHhqAaLM
R8n/7pnyVCNUWhSCZR9M0wf4FcpebQLEmwJJw1WTJ/xdVy8THeuFNL+svMfu//TP//sTlsXnvFZK
6QB6316P/aH+AcU+/+kf/69n3kB/f05iQVAfRmbmBGnsFmctKdODyARxTgAbJtCwMgatklQjqMwQ
eAzbjI6K9EpW+iQmvYxpvIenflgu7xdagdJqYNE/KSQIZ/cH+L79NKS9vy+3RcN7kDKFgV92/xGF
/+FVAb4u2vP4JuAZ9AH4+Noe1NlXn/T1JP3/+l/+x3//D/CTGQAxw+nPF9X+zsXHn+f6rW48ZeQP
f3hscx88WRfev4P/3UUFQIjx489o+qWf0mWYT7dDv4M/Q19RnOOyWQqznNfXiL9EZGfe/89X1qe1
k7zW9skiTbyHO+UmWml9IIXJ1ciAmeEQbg95EMfZIKQ2VQ9oVal4v15SUO3jgYXMVfVyV6zcfYnX
JojugLcET+Kjsy29NAgvT9lBSbEfwCLPwnmklhHxt+VWvWP7qlulBKFqAx9+2gByi2+Psi89ZQxY
A1n2HlhRudtz982/vSsNLDajDLwr99SKknmQ7IKQsqoGuC/XhSo1dl3gokI1LrM+8MR7D1XkX+tK
2WMp5LfjaoMuMsv5OP4R7ZpV48jqicl30LMVHGKImGfOpZY3MJzXijlZ83dIEE5mwzgu6El3KNfN
ldTvzfeD/tCbKEZvqcx8L50sdarnScGucMdBA+oPamGReLtZt6+5ejgcrGvSGi9Eq2DJNcM0DXIg
05MxbVBJ2w1qC5/pSUwrZBhsQ8idw4zApboc0YQVNqaQJfa1edGU05lEZeRUQNZJY7GT8XrmNsYh
YikDwwzHgzCaHaiW4VObzYHsNdP6rtPj28RIWGdqFptsRhVjEqodalKk9gyK2FGYN8NnrXoYCWlT
3juYu26hOd3qzWJet7Kpeqg1ESGqrbBllFqFamBx0eQHfsYLiE4iCAkhEdLg5542iXhfrXveZuqJ
3lZc95cukuc1adDczXvrRr6Z+NPlehgqusuMCb05R5fbRur5ft0jFS9CxztvCm2aMYPP+wOxoHfe
duayKiMa6nC33dVzxlvyfXbDTVgjVQb9KGyHUXONroRD7kwMTjZ0VO+jsuJ0oq6ZJhrUxvjCacir
aCVMRK7fHDhxOxLZkCQRm8X8YL2d0bHT16aH/rYI7FWYZTsDsXs1Re2Nh8KMx3fWdDxYSFoaQLNk
ZG6mjLTdH+aCp4wZpZugRi+0dqlO9iJXQ9r7em/GpNu1ra3QRpdZN0iWag0GvCP7+5HVHm7RZbPv
LDEF8nb1IG1I6ihAWaIwGUfFtsua3KqPtuO5VSdGYADeycI9OhWKlUQWYcN18tZedlmZrHvaoWNs
CJfxYwtMAAqmYUsfcNqS1Vk/Gpu+0AMi84Vttugaw4VmMt60tZiw86ZhN3FgR9y2OdmQjdnMc2mG
xuR+mG33VndN+tC4wdXtgdmK0CFRWyDSoG9mCqohuXtAWwwiZeGs1i0a8jTz8bqlKVSgBPvFQJtw
A2e46cljXJol7ajPRUYCjTlfW7W1TouxbEV3HH9iuIGRDbWFaqBYL0kJqakI/ag/yI1t5u9ni5Cb
KALfqPVpRphLfBdf0d0dp0mYD4l2w7F5ThCpFU4EjT1v68Ow1WC2GwxoED7ISXnFkuYMDYRUNCYR
dSB4y9572HLFTUOul9JZ7dDUh7khDKG87/YnOuHWMVuMA2k/wndUoe0G4tphGCuOB3TId601nQ9E
trfe8Xm3FozJfrwVbZ7seqy2D2fp3DZJbhxDoq6tjdgR66bVZjwz59qiqOUcvSz6Us3vjCW9kwf1
ZL9hZvNi1fVQu2kvV7VOLPZq1MrkG9pyvAs9h182YqiR+hlCdmK33VuuuodtPCYoLG3os0ZmGNF4
uUsPnSlR22NzhwsbTWM/JkVquVkues29a+S5hI0G+arhmUxqQl5TktYNim112pZEqD62X0muXsfJ
ASVRxHBtL0Rm4LUsPts3c2qVx0mYD7x4lKxnwlSKebYnt3d6d50Zdgz1THQy08OkH8hpPt0bnCam
0siYiV4tOPhRNNUsf8/11xI14YeaRUpMfRbM6jnS6rS2tNDFeUEf1JQ5mHMbmsv7HRowxMFJeK2/
V6Rk4uVdmtb4eWBLuZ2rh1lWSO562mvLwPKH61GCr5zUs+VDV9VaqeFuLANjFH7RhbAV6k47637C
dPaGEUu+ggZ2jej3zLRYdfpB4LNx4PqM0YyXBTbqhLvB2iuWq7rqOVPC4yUqGHeGekREoQHNh4so
UrSNmrGDhja0O1NmNdqIOJpo/kJobKxeUl+OsDUbLtUx4W3n+bhL77v1vnVwZIGeNPqcHDVcihtz
JjRB5Nji6uNIrLlybdjsUQ0rn4yVVQ9t7qPlWGAHI9EhJCZAu9oYH8dNvq8DS+8Iq1XUWEutZoYc
DCEkD4MEquM7ckqh9XljzhYuHXuTIOpv5IHbnFGxsU96k8U6G6dDUhmTbkpm2qw3pzGLSjptfESj
dXuiFpmJjufOegsljakZauhUjLOiNivmznJW1/w4Shv1otHLabeo2ZulfmB7k0OYqct+pyuzykxc
+m2EI/zsgO9NyeYJw8SX0Hi6NTFFwvgF67AIMBKkl+9zUaHmPr7rkSovBWxY2IbUWOqbzUjy5U2r
291i9RXbn3eNGBvZZlyoI3W18SG70cu6aDxTbHlU2417etusNaJuE3Nsa4xbjjyNDXE5mHVb8bjX
IHvm9kA1FLtPjTopM+qvs5kU9xZdgt1bLUiYN6Sgm42na33uDAmMVToe3UIWZNJkqImkUCGOIa2Y
TzbcetH2ZwU5TUcttEkpAdELm4VFhvnYkbldpC4hwe/Lerwe9Edrku0yZAdr5LHZt1rtXrwvKLoz
SCQrMFiSsIauKLLdSdRZ4eaS2Iu4pDv4yHblRlxr4c09CmUxLS5Cno1HNOHw/a3fw/la29622tG0
WSPIlr/rZOqQczvMyAgOM8zudohEXSxWItbThDkxd1h5PXfiQReB7HYrC9YJcENkgo0kFj2M+Y3f
XEa0KR8yn29YnZFc7893+s6LcWUpTpjWJpH23qYxjcXc6EeWPUuZbdNb29CU98fLxcZnFLaNN3A6
sM3xQTjsWbWG5118jggjjRvtOlOwsLeKJj5qdydJXhQ1n+gVm6ZHd4uM8I2uj7AZRJEOMJe+U+9s
F31JdFSS0/nOHhNXBZa2t+wqV5HAsqjVuIUiq3yYgCVqV7e6HJELljvcoOJgky4O3sDqR9AI3/bJ
EOiKNV06wSDEMK5poqswCehoPNPn2mHk1ILtfNj0e7OZtDrk6FwzUa5eWOrAk3dMZjr01ne3sRlC
0wEbGiE6NoU9xQ53YjZakAdss2zlq6aZgA926s7zdLYWNn3RZkWX7QTdVdLQdYTcFp2lkkr7YtpY
EiuvDnXQjRrRlteJm16IqtF4mM1qu84Ct/lps+im6pqd8+MRiq9E2pH4FkpgsjXNKR8sZr0xsndX
007AejRZUqbxw7jRpCeeL+h2P1nnnjRG8cZiKmUzRCSaNYkrDEXf5gjJdIZUjXX8+RDPEB7lSZcZ
tEb8cB9SzmHHzSfQ2DCLbUS6mdyZFHifYoNhNEc9lWf0Im0NuGFRk3djmdkGnSBOVSLgTB41xypI
bbr5dLmNwt4sq5FYtrBoaNpC8RnNqgrGocM6j3ZWBiYPC8vwYmyCKIQoBWZ/Y0fWVuq2iwzhlCWK
L/r0UBt6Y2lgdOJ0grZ1lZJ2HYic71CngWO4HW7BAs0VzKovHeidSu0WPDf397aZ7Q9KVyRwSxeo
vo6StGnMaqTKmlGfsbFpjViLrQPdnhjQMNKVtjddWS2DZPcSiBrNzWEn4SumjzL96azGJMIud7eO
xuQHRO/v2Z3Cug6/szmOTSWwfBfLRdYZMGi2hPTuqj9e5/3uIJ1kHu7oh1xYqTm7EMn6weyJeTyz
NWykBVK7U0s5kkkQbdq2OjtdYCcjNVqWhwV2xnKv2zNo4/INnfRaG9TuhdtOre8ciByll/MoJ2oC
SFbJxq611DOhP6Bbxc6QwuVKFakeZ4rrAc5EXMztWRDKS/tVDiVrpotyKRvabs/R7UUrNtrhoeYf
VHOMFj0ExBOIQ2x0rz+fcdR0hAyoLtok+7QqHTZks1bLzJUKopSszc+hbbab5LpaaGE2QIcjecg0
Ri3fExRH4rrBkhy0m3J/hdH8VB4xykiX0FByp6ti6jfHg2mHwmxHNMjmYjQOTKgn7lJpylMmbojE
bhbI61Rcokm9y5uyqk4iuUdkikXlU54bzkB8fqi3vIDpFuLYZBveAFWpWgpWO9dHEBrKEKo16S0Z
3dbwWjDEDSRf0jUc9Zx1t7Xw0UHc7lNk98BrXQGJA5yZ2nvRp7m6X6c4tr9MWhgl76nuKj/0IEFZ
TTzNyRxyg48OfbHpNzWdJcareTzRUlnCt4XU3miTupja674rScWwq4bz6S42pX1et8P5atpSk3aO
JDVoIvUyotFthS4zSbHh0lK4HjvkaZBH5HsQLg2nq1BuIwZlMyTqK7LQphRn2tnzOMVGi5AMulzX
zaWNEDBLiN6ojCtstQmiLwfTusSqUSwgjEOLWmeWEUsp1w+ewnFGc6141DCfCvu2HPstqRc0uvg6
jNq2FGy16X4QiJC/s/u2NrKS9XzrdEJzh3Q4X+/mIrkfJsN2sHWE3aAmU6Oe0G43ZuMGvQksZVms
avhwY9ChlboS3sl9uqB6EL1KncytNQRlP5nUTBzd2pQwT1YrAhVWVFKbs0GN2s+1sTI7eHvEj0l/
Ym2nAYjnyXkyrdXDDUH77U0Sbg1Ineg4V6AKNydXlAs8sKQmORq5kxCrb4imwpF4H4nxSbjgcF2Z
x7u+vsGn+6YqrjiNSFmn2W9GssOP6YUKoRaWSElt1WmuBiD93SzVxaqg571tDWMP8WKChD19AIJ4
ZD4JJXobbJgkE/eF2mn2dKW1G6+ErGFFieGNdygU+GFtXJBxe93k3BouL6dUbZQghoY1Mw1TAW9+
BNLrsZP53EzxElq1UHrEzXCzMR4GOlNLSXa3Cce9Zo5BW2I+juYTz2L5hkxSere50w7mhFPoNT/3
d1hs4fNxHGuI7nV2bujVxJVxmK9HbB43k/lMN3YbdWZTo7ThGtCgKa6mI8qfF6aP6bS2RVaJjqZF
IoTEKF3HOEkt3HbCpuzW6KuNgF76s43fn2UpKsY7bTxwtpsphVvdrYxCOsmkOIh0uAgbjnC3YXV9
IUb2NamBx1wzNBKvZ2LoYG0dBus9WDBZCt1NkzbOErrfzC2cXvSQRUt29RnWhLw+zYahjOo7Klbs
iJtlYyzjuslgrWPiwltw60adQ5QG30bQQ4AMVuaiRgmrQaocdqRuNsmhHftjREbGXgCJ/TB2DXdG
zAtV0AO9O+NBGDs+bF0NxZrjltCsm4txF480YeMAGS0iNOpZM6q2UBNcCRqdcN5Hw5rXnLsslEW4
3O8IEtfQVppGGSaqE7FEpOvUrKOD3TDZJ1rP8mV0F85ioHLTdQ0/UEgKFiLM8hPlYEnpfG/tVnPi
ALmk3JvPRZqOtKYkk0u7PvTF9mKqJ2KrpWC0152ISSbMpHSxy8a72mxai+vNTAl8dA5ysgQjxdq0
P17V5msNwjZhOm+ZLGLxPWxOG6RsrdqzNfAwPqLkGyRl/bhHL4ezruV6Nb4v8Eo+R5EBQuysIUkj
NVb0xOggoo09Aq1EnnEbpK+TvouMzKwx8wULL0h+lJGb2qKxx4e15cFH4tUBmY9IZCjoiJuNrALx
RNI69Mpkovytg+qQYCF7xEJjwartfbEJ2jVi8tCsUXW2ripf7kTP6I0BBtE1WUfQjWAVB5Cjk9qh
hzYOCMnlnrhtIlkD0VNfP4j7Xj+YZ4BcK2v0/QboAI+shjXqMO3WrDuOBkErnQ650O97JNl3vYKA
EMVaCFFXHHX7cQeoAmqstuo+2jV8qtuXxj1llmmEZmZ5rUZsUn2Po8WmXawmfl8bLNIDLU/Ew3Az
3u1nIgKNnFGrDUJQfuLqK/9AJktLGgxXqkm5hu4yjSil3HWb8KSecyBXBshbaLKDumTPiN2sN8kS
ZYkFHEiGWm4GZZvemlZ5buWytfaM0w+tjbQVl7oXtFeu10VHi1TLpuEmjDdZfdfaocWBcIOee1B7
elK3vRarSZGC+3KI+pAJcsv60J5Lu0OjLxl7kM4RNjcdp42pJff3i9S1TX3UI3uTOEa2m7nZHYZ8
h212XYlXcNIWVAIIdCVMRyYF7UWnrZFM5OL9UVuUmcmE2OVkgcwtZWbP6lhkk2LIOpmHsPsOMex0
Mw6ldoO45deNQ+BqhnhoJHRNEQ/cAgpQIBAbnYmBTYfDpdIUIknZ080mRgyZpEFn6Q6pxXiXHXlD
o6nsZ/3QtjsTzFSs3kiKzA1v7hg7HmON4RyKAPU1XjuQCuYsAmOyzNOR05jos2lrpE/9nr1b5iqz
GFMODTLocDn01c6Wbs9aJjJJO3we+cwK6I68GPoSNFKZZn9Ke4LN6+1cH3eC8WK0brJaS9EmB05u
u3ic8onbVjyJNcQ2beqoTq3dzOyBgD2dH2ZUr262O+yAa0J60nKkKJNVP8Z9LNuxZnO63y1Qj2u1
sGk4t+sJ2kOYfbINdt2GkUiKTWjx4GDuzHEKMm3UJabjiO8utgoLUUM/nZv0YEI2BGET7s14KWEE
X0vWJmVneFQj+FbCkbbZGvo5LyZNTlyq21bdmBgbbhjKqoiLjckksfx8Ai1orDvgE8LZ961Dv7np
rNJO0ncCu0DW07A33PfbLZZbROxiuc66abOlqIU5qXvdlt0PRmpntptNI3KO5NKyB61bWjIaEGhY
tw8EF3rrumgrIIFlmAXVLhCEW9Gc30ScDmfKQ7FHEO2Q8B1UM/E+XjdH7DShOS3gIi7fOxAWDBOS
J4etfavVTfEtmoEUrd1dHBoHqrblDvVNSBlh47Cobfq9HZc1OEUYt5B2R95as8x2JjkVroeWxWwG
LQjLlVGbyZz5SMPD9Z4M17GA1SSiuRrV3F5aeDIpZ22a1LotUs+6pKbjBxKlU6GNtmnFX8xHtr4I
FmGymRdQNLfayoqSgk0vn0cMsdT2DGv5ESczIC1aYLqKymtLMQoco9DWuj4y/TDaHTprbnhocFlb
PhzSOrHdsLoJQipl4W1mw7SGjgl6E06SpbGXmkYnC5PIDQ7sdsTkISGse0LDDMRW3QMhvZmxDc7n
u1LeRkgfCQa4ki9BDA+l4p7Z1mqrZrsVLamIrwcDFEQcRc72SVZInLon52yDwFJb6necSWRrIGtb
ofGOteNepNgLeST5S3eEWwMbSrt2q7Ejo5Z4cIqJ2NF0jcXXS343bRcd3/CCsIHajSEqJe2lgInS
Xs57TToVjYY3yRZkgQU7cUJ2iAxrraD1sp8Zc41bxhvGNHlVVlKNdhvmGlX1TEr1aR7PBxNtQ0y2
2WSY18S1NNsyGsVPZlo7LhZswIX8KtP3CtaFUmzU99ocaazw4STd9Mc0i7YWM8fk5vgi3Ct5Yijs
YmTtpn22yBczldmosuaxnj9Ka9YqE/uH1cDTig6XkNAuMwcowlBbuY8N3cSyBcaq6wSqeVKrezi0
dY8tsIbc3I36QzGYCbnSmHtWhhkS623EAZWPqO2C8s2dNkegWHPFSau/8HtcJAjSrNU2eb+N72cN
aWwro3XP3DMU46xGi67PO/0dNUIKN8yRZcH2LZ6KrXyyzk3CHKTuFNKFHdXY+2lHWzEH053qI23g
xVNu7e1biDhr18zhfhu3Fyt3mjMH7GBtGGPkIEGHdJZrjOHZoN6XOpg/tadtqGVPtkpNtvvCaizh
wg64a8HXDR3EQlJrk0qjJbch9EN31BiQFDKipf6Y4AQOJeNZoa8OQ2I0JSJ7LdX6qg4VkjHqOQq/
El2+3bf0IA34NSrlPXzcGxgUYe4b214jzw1OmCRdxh1SvN6pR+gqEhW1ZzbpnbxIieHKoQQeGvjt
fCjxI9apC7NZ3QEB+nBBEnOv0AkJWXWJenigeqIiF0gfiH6De/lCrdUNGkVcQdB3/j7cb9DacJwf
JAhzJiuyW+/2Rr3tdD/iwjCZejnviv5yg9khut9lPBc1e2QiNruZp1k8vfGEuF9P+vvmSDcmNQ7P
BzVj3V0oUKI4QbHa1chU0ukaV+f5RTig+6yirwRhqYteh3U5ahcXsppLrZnrrVk1BNY1wJvbFt6u
jRTCG6ybOjuU+lARd5EQnUWI1xX7k5ph1eaoTDFqHNsbsYvQjKJ3te5qjcWMGu3whoZni3oSYyw/
xpMF1eXFib2ktjvgOgaQ2RU4doy6GJMMjQMQC58S7THbyfuHOBEP+HYlx7XVDHNxrcu3SGc+bcoj
D5NraRGoA1qn9jUKd5ENyBh8SF33RSK27UMPAdHuKoonrWzfTSe50fP8wh7X0o7aZ5daLdH3fb9D
FDlY/IBvW4tjVJb3QN04SRr5RHs93kE7eU6jimVb4vgwZ5U5gy59iddY11fUrDdYk2KcoiwddJOY
yCbOEN9MXL6xQtPmduIHTcKgUKGGainD9lCoqHGbSVgsw51DzvahS+89yqqJfQE4Xnw211vN8ToR
FrQIEvHOgaxtvN5s12gunLwxt4ZrvRGadZ7gCGkf6xAS7XZN3KSxmB27thKH7WXPyY2W2dYxQZFt
kAMFAd3dOJ1kMy0CLSmmzdlSNsd2G7doPKR0f+IjGCLHfBOiuz0u7+K1+SowEQSkCsuIRlAhMJTu
LN7ru41nKW0aQZD9ZGtQeIrpe5ceak48LRpYRomkOEEYUk2yQd2ElgTwnGyjJtabVC2sBX1xQSF7
ubPl8pFkisWI1sz6IG3xUtJJjW1f6EooEobZtM4Uy91B17BaIASdDhMPC2gVhotktmdGQe1gRz2b
5vdIq9XoZNyG4oJwm2thZ130OtS6t8ASmzX7asTESJeS/XlXRONtvmVbenuC8IMalI/rWJchmU42
GzbXa/lAaKTPGonJEnyooakUawc7NYJQVex6qvFrUi6CET0a77tLnWUdS81oabBsOZy7gHpLf+ml
ftBOmm7R2eieJpAtt9HTD4kzlY29LeUUG/S6frofbwbCZGvL7a4+DjRy3VmoXVUbNLkg7rJkjDag
jVzIw7ktutGKS9Fihjd6u8M0t/Ml2x6AhD5KOYI0pqikmnRAm724ZXpWt5YcZvtR3rfny65uIWNx
sC0MsAhv9mQjnYRuj2DFdVsd5C2CYZiP0K+J//3F+O9/Ae77XP4c/DdBgOcYhqLUDf/91yg3/Pcv
Z+SG/77hv2/47xv++4b/vuG/b/jvG/77hv++4b9/LtK64b9v+O8b/vvXt7Mb/vuG/77hv2/477+1
I/rTDf99w3/f8N83/PcN/33Df9/w3zf8998l/rt3w3/f8N83/PcN/33Df9/w3zf89w3/fcN/3/Df
N/z3Df99w3/f8N83/PcN/33Df9/w3zf89w3/fcN/3/DfN/z3Df99w3/f8N83/PcN/33Df9/w3zf8
979O/Pf7xIx/hf//G6VQ8OwR/42V//83Wcdv+O+/Rnkd//3xL1l+AQBc1XUzTFRfN+FSyeIK9ICY
iHg6f3/SzvKccOimcXkcDNiwkxRXKI8/Q5MBRZPU/1ChL9e/4jhni/mLS/QVJPrxSPXHu1+Pm7sz
mGnMjC5gpvegAXJqgDyCmX457AkSGVn+WP8O7jL88GMdeigPQJXItsvRyj/983+Cv/nj3XdwdXRX
lms1+N278qBciXwtD7w9lBJ41uQ/l02OJ+NAs7LvF82g8qRVlDyUp7eeQ+nMWK+wdHCu+gn4hIHh
47VjJTB2Vc0Oko9HSG110usZDrUcq6zxzb+pqhxPvoIH5bFGc1d+KTuvTrqWxwMrxiuMHRj8M/y2
OlR2bPDu7uqE4BcLGK6SxKWPD4/nWE+dVQN+W1J16vkOepRDecizFEb8Ell4EUd5yr4Sx5ml++rc
ZPn4C4zcvUbXm1OTN4/nuitKTocO/+l/+zv5d3ei6MpdPXdVlyqnSyo+PJ7VL+3k8+X96Qhy+f5o
q5dXf3M2r/gtMar3dRQuHWRJbnWa+6gUFRjHiauDhmlSQjtO9APbOH74oWz66brp3SvKBd+dRAF8
yqnru0dQCJBKqVb76ydPFevU+gkl11r2+L5Urqs6J+awCn/1CLlSM9DsS+xgn55Uvrt2GvAdeOVU
15CIjNK7g+tXwK7TYDgMd50oTsrpr87MXkFWasdzvK8Ni3+6bgZWyKtmfzg2u4OUjqyckY9vvW2F
VLg33t1BSaSG8JtHUO2l4ue7N3BnwSsQ1OUn4JkwVcq2ZzDbx6d1n0zB2aOV3vPdWXO/+fHST2no
8BEzAnzbI47l7Loe58+6MAZqB1HpnvQX1R+n8+LD3jx2+ua70oeVpnQ1/s/R9PTw8y+iS3u1yWu0
Pe38dfqOGkHAsGzqAbClcqgnYMIrBVk7ybflKeQzqu8VHSE+XXf0qCSg6R0kd9rCmP0LTPBjR6/N
cDnWC0HGj1Q9m+Gr6l+eYFDpUX7Xw/8MTdnPT/EVZYZjVP7hJOCXZKX+F2e3tPjHrs4TSwJTj0zg
016ZzspwVRt4kNdmkvz09ZZXpo49t/XupCP3vjrP2C+05HNHf4YlV0RXIHxdrcDKv8iQr0RSHb9/
7ObRbB6JgV7xY9jFmij4K2gYME1Ho/6iDVFfBNPoagmX+lmn8sXBX0rrJX0ncNcRIuB/zTReJa6E
wgVpEqbJV9wNDcNMZJ8hGOUNQ6+Igf70rFLpQMYKP+4MQfh+jn0e1Mh+KIOeh2++uYOYCffnuJf7
+0s/92UfRzs+jvFSKR3rcgvHaZynYr9uewUTu5i5nzjlZSiA4Kqf0pWX2COQeB5BHiX0+OtjOJ3S
BVQw358sV7V/Sv0ImLztOwfT+MnxM9V1jFfGPoFIQF3TycC4ZdAUmZvjNJ46hMsO4beP4q4ge07k
lZdFPUJwTkqgH29kCZJzrYqtx8bfnZSgAp6dGTmBccDcNmC4A4KV++OdSF9Vg8anV6venTDGD2WU
U863VWJJn8z1F29bqK5HgO8rgNUbkPC9eYaxXpvAeO59GD1O+gU8ejXicyzgC7GUSUpiVu65BESd
cTwgqQBh4MWlllsK5oW7srIaOXFl4meBn2DJZYR0yutOZFw9+Qvo+it54vXIp3zxhRD+/F6vqX+S
hV4N95iNXtU+htyPOeeL4PuCeDrerWDGlYtNzqI/J6/X4zxJYl9E6680uCzRRxjnkwFO1Z+Q/Kjy
TfgEVCtBfq5aAPt4Td2bnx6rHa/yOVU+3vTRFqZj5S+s7rkO37vH6xbuQVwBlzcIHKfkMmI5IWBN
QB9n4GoJeabiR0T0U0X/Km3IyzUGBJlf6/ayBJUJ+2lRQeuPq+4Jn31awl4RM1p/XGMdPzHtyEmA
/z278tfh5Y+29FwEz2o/G/8RHf6S0S+0LOOQ0gVfwYRBTuepLnAYwCGfWX5MiatNw7jwE3V/uo/l
FaYf0+BjzTuoalZirr/C3Gn8CgMYw+cW12O9ZOvU5ggGfb3NiQWQ+LaPyOcyeDBAJFtBwivOE9UL
S5B6GY+doNTfnub+MfgwoyiIXuMWZMmv9XwHtYXJZCoqD+fdyXPsCtReD5+IorzY4kllYND62gsM
uLZ/9eWImQzKOyR+0XUFL5q/uL3g9zA/EoWJwoyVD+db+Y7raoUaPy2/SbVhUGqb4ejVrkJ5BUuF
mo7KcFP1C9BTBbvXU1c9Xq8Av61wpNXtXgn8v9JU1SZ+9x6WgxL6f4KjVyjQPx4DVj/w74GYkuKP
VXdH66n6AiGM5TrH3pxyp7yq/0hEKfzIc3wnBiSorlu8h5SR+HDi/8kMlPeb3GewV11c8ihNIJzy
nsbx5B8+evCPx1sev4NBNpTAn8Hzt78rJwXorGv6drJ++0393ff1y/VvH+NUK6+u/Kb+Lfot+u54
w1T08a3+8eMdc/dv7lp3H8Dv0/Nv6h+BfVwaYKfHoP+PaPmxHO5EQPW5M2bBd8eqSHh3XAQw8Ob1
Ga5uLbji/WRvgHIve/nqtR7K6hUg+4Itf9Lmu8tW8tcU9fmlO2Wbi128tntzfvdKcH3d7As0fyG7
u+r0eZT74saEny73I7ySxJxfnX3l0difBbq/JJO53M9QeZVLBvOE0Kvc7+dZP28f/z1uqyqCwgxP
l4/IMlyr/iJR3jty2hyemHHqJvHxugm5utilavL5hAcvr3cpm3w+g/7/Dnk8xjEVlceYsn7at63s
tF7dnnS84OJv/UfPW7mUx7//Be+BD/tVxij/yl/e8f763/9BIav730lQiybr1G/qKEFgt/vf/yrl
9Ferr/wxF4LsAEbfYzez/f9judi/ByLb93bwa4zxM/aP4jj23P5J+nb+569SyiuZyi3ocvohyPGq
q0HfQr+9s7zkDvwK4vLn8W568PEdBFmpr1fVq0MCv63u8vnwEQ7i9wz4+AP64RME/RZB4BHIQUAW
Xf1vCO+h3zpWmTC8Lau/gz9+PMYD5bcf6p/K73f392XNu+ePjw/BQL8FFL0Xy1zA9d/eXQ6QvHv+
Ji231D+8fA7D5zbwDy+20v7hvGX8/Sf4hzJKIUBK+0NJx/v37z9VnR3vRId++/nI3jR+fpDpxSGm
JPjCju1RHE+Zf0rQkeMnMvv+I8h1yqdP2Ko6QT+VBF4oBCQ+4/28x3HmsmIIzFi52/sWe/eUqSuy
zVd2g18Sf5TXK5N0enE9GHE1GmtaKoh6Pxw3Eo6XQgWne5Bi8NuHA626Ounp6NdDnBTzfT9wjrL4
FgTTdyCu/nxbrW7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7lVm7l
X0n5/wDdZYiWAMgAAA==
